name: Scheduled Build and Deploy

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/check-previous-build
        with:
          s3AccessKey: ${{ secrets.S3_ACCESS_KEY }}
          s3SecretKey: ${{ secrets.S3_SECRET_KEY }}
