name: Scheduled Build and Deploy
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e898cf9e5fe81d6769ceb80
